"""Prompt templates used by the persona extraction LLM."""

SYSTEM_PROMPT = (
    "You extract persona data into the PersonaProfileModel schema. "
    "persona_id must be lowercase kebab-case (letters/numbers/hyphens only), "
    "matching the page if shown; otherwise derive from the segment name and locale "
    "(e.g., curious-connoisseurs). "
    "Top-level keys: persona_id, segment_name, locale, "
    "source_reference{document,pages,extraction_notes}, "
    "core_profile_overview{market_impact{population_share_percentage,value_share_percentage,"
    "spend_at_home_index},identity_summary{demographics,psychographics},"
    "sustainability_attitude{statement,index},"
    "consumption_habits{at_home{volume{average_daily_coffees,index},behavior_description},"
    "out_of_home{volume{average_daily_coffees,index},behavior_description}},"
    "shopping_attitude{statement,index},innovation_interest{summary}}, "
    "demographics{gender_distribution{female{percentage,index},male{percentage,index}},"
    "age_distribution[{range,percentage,index}],average_age,"
    "household_size[{members,percentage,index}],"
    "region_distribution[{region,percentage,index}],"
    "area_of_living[{area,percentage,index}],"
    "income_distribution{low{percentage,index},medium{percentage,index},high{percentage,index},"
    "average_income_eur,average_income_index,income_brackets[{range,percentage,index}]},"
    "education_level[{level,percentage,index}],profession_distribution[{role,percentage,index}],"
    "coffee_purchase_decision{primary_decision_maker{percentage,index},"
    "shared_decision_maker{percentage,index}}}, "
    "values_and_attitudes{lifestyle_statements[{statement,agreement_percentage,index}],"
    "coffee_attitudes[{statement,agreement_percentage,index}]}, "
    "sustainability_attitudes[{statement,agreement_percentage,index}], "
    "coffee_consumption_traits{needstates{at_home[{label,percentage,index}],"
    "out_of_home[{label,percentage,index}]},consumption_moment{at_home_only{percentage,index},"
    "out_of_home_only{percentage,index},combined{percentage,index}},"
    "time_of_consumption{at_home[{moment,percentage,index}],"
    "out_of_home[{moment,percentage,index}]},"
    "coffee_choice_motivations[{reason,total_segment{percentage,index},"
    "bean_users{percentage,index}}],types_of_coffee_drinks_consumed[{drink,percentage,index}],"
    "type_of_coffee_used[{type,percentage,index}],preparation_method[{system,percentage,index}],"
    "consumption_metrics{average_daily_coffees_at_home{value,index},"
    "average_daily_coffees_out_of_home{value,index}},"
    "purchasing_habits{amount_spend_per_purchase[{bracket,percentage,index}],"
    "average_spend{value_eur,index},shopping_frequency[{frequency,percentage,index}],"
    "average_frequency_days{value,index}},"
    "channel_preferences{physical_and_general[{channel,percentage,index}],"
    "online_breakdown[{site_type,percentage,index}]},"
    "brand_landscape{top_competitors_household_penetration[{brand,percentage,index}],"
    "sub_brand_deep_dive[{brand_name:[{sub_brand,percentage,index}]}]}, "
    "brand_perception{brands[{brand_name,brand_share_percentage,metrics{brand_share_percentage,"
    "buy_regularly_score,trial_score,awareness_score},"
    "conversion_rates{trial_to_buy_regularly,awareness_to_trial},"
    "sub_brand_funnels[{sub_brand_name,metrics{brand_share_percentage,awareness,trial,"
    "buy_regularly},conversion_rates{awareness_to_trial,trial_to_buy_regularly}}]}]}, "
    "machine_ownership_behavior{penetration_methods[{method,percentage,index}],"
    "machine_currently_owned[{machine,percentage,index}],"
    "machine_previously_owned[{machine,percentage,index}],"
    "reasons_for_switching_machineS[{reason,percentage,index}],"
    "capsule_machine_motivations{reasons_for_owning_machine[{reason,percentage,index}],"
    "reasons_for_not_owning_machine[{reason,percentage,index}]},"
    "capsule_machine_brand_ownership[{brand,percentage,index}],"
    "machine_price_sensitivity{"
    "electric_machine_with_beans_investment[{price_bracket,percentage,index}],"
    "electric_machine_with_capsules_investment[{price_bracket,percentage,index}]}}, "
    "innovation{top_concepts[{rank,concept_description,percentage,index}]}, "
    "lifestyle{attitudes[{statement,agreement_percentage,index_vs_coffee_drinkers,"
    "index_vs_all_adults}]}, "
    "sport_and_leisure{outings_and_activities[{activity,percentage,index_vs_coffee,"
    "index_vs_adults}],"
    "hobbies_and_interests[{activity,percentage,index_vs_coffee,index_vs_adults}],"
    "leisure_attitudes[{statement,percentage,index_vs_coffee,index_vs_adults}],"
    "sports{interest_in_sports[{sport,percentage,index_vs_coffee,index_vs_adults}],"
    "active_participation_sports[{sport,percentage,index_vs_coffee,index_vs_adults}],"
    "active_participation_fitness[{activity,percentage,index_vs_coffee,index_vs_adults}]}}, "
    "media{media_penetration_channels[{channel,penetration_percentage,index_vs_coffee_drinkers,"
    "index_vs_all_adults}],technology_attitudes[{statement,agreement_percentage,"
    "index_vs_coffee_drinkers,index_vs_all_adults}],"
    "channel_usage_intensity[{channel,usage_level,percentage,index_vs_coffee_drinkers,"
    "index_vs_all_adults}],content_preferences{television_genres[{genre,percentage,"
    "index_vs_coffee_drinkers,index_vs_all_adults}],film_genres[{genre,percentage,"
    "index_vs_coffee_drinkers,index_vs_all_adults}],podcast_genres[{genre,percentage,"
    "index_vs_coffee_drinkers,index_vs_all_adults}],radio_programmes[{genre,percentage,"
    "index_vs_coffee_drinkers,index_vs_all_adults}],"
    "newspaper_topics[{topic,percentage,index_vs_coffee_drinkers,index_vs_all_adults}]},"
    "internet_consumption_profile{social_media_behavior{time_spent_frequency[{frequency,"
    "percentage,vs_coffee_drinkers}],brands_used[{platform,penetration,index_vs_coffee,"
    "index_vs_adults}]},"
    "online_research_topics[{topic,percentage,description}],"
    "device_usage[{device,penetration,index_vs_coffee,index_vs_adults}],"
    "website_visitation_last_4_weeks[{site,penetration,index_vs_coffee,index_vs_adults}],"
    "online_activities_daily[{activity,penetration,index_vs_coffee}]}}. "
    "Return ONLY JSON with keys persona_id, patch, page, notes. "
    "Respond with a single JSON object only; no prose or markdown. "
    "Use numbers for numeric values. "
    "Never include null/empty keys—omit any field not present on the page. "
    "If no persona data appears, return persona_id null and patch {} (no null fields)."
)
